services:
  - type: web
    name: task-management-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromDatabase: taskdb
        property: host
      - key: DB_PORT
        fromDatabase: taskdb
        property: port
      - key: DB_NAME
        fromDatabase: taskdb
        property: database
      - key: DB_USER
        fromDatabase: taskdb
        property: user
      - key: DB_PASSWORD
        fromDatabase: taskdb
        property: password

databases:
  - name: taskdb
    plan: free
